name: Firmware build (NTAG215+amiitool)

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:

  # Builds with DFU_UPDATE_BUILD=1
  build_dfu:
    runs-on: ubuntu-20.04
    strategy:
      # devices to build for
      matrix:
        board: [PUCKJS, PIXLJS, BANGLEJS, BANGLEJS2, PUCKJS_MINIMAL, PUCKJS_LITE, AMILOOP_MINIMAL]
        config:
          - { bootloader: 1, dfu_update_build: 0 }
          - { bootloader: 0, dfu_update_build: 1 }
      # try and build for all devices even if one fails
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: make {{ matrix.board }} - BOOTLOADER=${{ matrix.config.bootloader}} - DFU_UPDATE_BUILD=${{ matrix.config.dfu_update_build }}
      env:
        TRAVIS: 1
        RELEASE: 1
        USE_AMIITOOL: 1
        USE_NTAG215: 1
        BOARD: ${{ matrix.board }}
      run: |
        source ./scripts/provision.sh  ${{ matrix.board }}
        BOOTLOADER=${{ matrix.config.bootloader}} make
        make clean
        DFU_UPDATE_BUILD=${{ matrix.config.dfu_update_build }} make
    - name: Upload ${{ matrix.board }} build artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ matrix.board }} - BOOTLOADER=${{ matrix.config.bootloader}} - DFU_UPDATE_BUILD=${{ matrix.config.dfu_update_build }}
        path: |
          bin/*.bin
          bin/*.hex
          bin/*.tgz
          bin/*.zip
          *.bin
          *.hex
          *.tgz
          *.zip


# Disable doc building for now
#  docs:
#    runs-on: ubuntu-20.04
#    steps:
#    - name: makedocs
#      run: make docs
